SectionDevice."Speaker" {
	Comment "Speaker"

	ConflictingDevice [
		"Headphones"
	]

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId}"
	}

	EnableSequence [
		cset "name='Speaker Switch' on"
        cset "name='OUT2 Switch' on"
	]

	DisableSequence [
		cset "name='Speaker Switch' off"
        cset "name='OUT2 Switch' off"
	]
}

SectionDevice."Mic" {
	Comment "Internal Microphone"

	ConflictingDevice [
		"Headset"
	]

	Value {
		CapturePriority 100
		CapturePCM "hw:${CardId}"
	}

	EnableSequence [
		cset "name='Differential Mux' Line 2"
		cset "name='Main Mic Switch' on"
	]

	DisableSequence [
		cset "name='Main Mic Switch' off"
	]
}

SectionDevice."Headphones" {
	Comment "Headphones"

	ConflictingDevice [
		"Speaker"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId}"
		JackControl "Headphone Jack"
		JackHWMute "Speaker"
	}

	EnableSequence [
		cset "name='Headphone Switch' on"
        cset "name='OUT1 Switch' on"
	]
	DisableSequence [
		cset "name='Headphone Switch' off"
        cset "name='OUT1 Switch' off"
	]
}

SectionDevice."Headset" {
	Comment "Headset Microphone"

	ConflictingDevice [
		"Mic"
	]

	Value {
		CapturePriority 200
		CapturePCM "hw:${CardId}"
		JackControl "Headset Mic Jack"
		JackHWMute "Mic"
	}

	EnableSequence [
		cset "name='Differential Mux' Line 1"
		cset "name='Headset Mic Switch' on"
        cset "name='OUT1 Switch' on"
	]

	DisableSequence [
		cset "name='Headset Mic Switch' off"
        cset "name='OUT1 Switch' off"
	]
}
